#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/User.cshtml")]
    public partial class User : System.Web.Mvc.WebViewPage<Piranha.Manager.Models.UserEditModel>
    {
        public User()
        {
        }
        public override void Execute()
        {
DefineSection("Toolbar", () => {

WriteLiteral("\r\n");

            
            #line 3 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" class=\"save submit\"");

WriteLiteral(">");

            
            #line 7 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 263), Tuple.Create("\"", 318)
            
            #line 8 "..\..\Areas\Manager\Views\Settings\User.cshtml"
, Tuple.Create(Tuple.Create("", 270), Tuple.Create<System.Object, System.Int32>(Url.Action("deleteuser", new { id = Model.Id })
            
            #line default
            #line hidden
, 270), false)
);

WriteLiteral(" class=\"delete\"");

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                                                     Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 403), Tuple.Create("\"", 433)
            
            #line 9 "..\..\Areas\Manager\Views\Settings\User.cshtml"
, Tuple.Create(Tuple.Create("", 410), Tuple.Create<System.Object, System.Int32>(Url.Action("userlist")
            
            #line default
            #line hidden
, 410), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 9 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 514), Tuple.Create("\"", 563)
            
            #line 10 "..\..\Areas\Manager\Views\Settings\User.cshtml"
, Tuple.Create(Tuple.Create("", 521), Tuple.Create<System.Object, System.Int32>(Url.Action("user", new { id = Model.Id })
            
            #line default
            #line hidden
, 521), false)
);

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 10 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                                                Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

DefineSection("Head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 755), Tuple.Create("\"", 830)
, Tuple.Create(Tuple.Create("", 761), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/ext/jquery-ui-1.9.2.custom.min.js")
, 761), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        function disableLockedUntil() {
            $('#User_LockedUntil').val('').attr('disabled', true);
        }
        function enableLockedUntil() {
            $('#User_LockedUntil').val('').removeAttr('disabled');
        }

        $(document).ready(function () {
            $('#User_Login').focus();

            if (!$('#User_IsLocked').is(':checked')) {
                disableLockedUntil();
            }
            $('#User_IsLocked').click(function () {
                if (!$(this).is(':checked'))
                    disableLockedUntil();
                else enableLockedUntil();
            });
            $('.datepicker input').datepicker({
                dateFormat: ""yy-mm-dd""
            });
        });
    </script>
");

});

            
            #line 43 "..\..\Areas\Manager\Views\Settings\User.cshtml"
   Html.BeginForm() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"grid_9\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 47 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                          Write(Piranha.Resources.Settings.UserInfo);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Login, Piranha.Resources.Settings.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 53 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.Login));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 57 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Firstname, Piranha.Resources.Settings.Firstname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 59 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.Firstname));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    ");

            
            #line 60 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.Firstname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Surname, Piranha.Resources.Settings.Surname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 65 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.Surname));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    ");

            
            #line 66 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.Surname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 69 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Email, Piranha.Resources.Settings.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 71 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    ");

            
            #line 72 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 75 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.GroupId, Piranha.Resources.Global.Group));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 77 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.DropDownListFor(m => m.GroupId, new SelectList(Model.UserGroups, "Id", "Name", Model.GroupId)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 83 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                          Write(Piranha.Resources.Settings.Account);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                <li>");

            
            #line 86 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.IsLocked, Piranha.Resources.Settings.Locked));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <p>");

            
            #line 87 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                  Write(Html.CheckBoxFor(m => m.IsLocked));

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 87 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                      Write(Piranha.Resources.Settings.LockedInfo);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                </li>\r\n                <li>");

            
            #line 89 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.LockedUntil, Piranha.Resources.Settings.LockedUntil));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input datepicker\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 91 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.EditorFor(m => m.LockedUntil));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");

            
            #line 96 "..\..\Areas\Manager\Views\Settings\User.cshtml"
    
            
            #line default
            #line hidden
            
            #line 96 "..\..\Areas\Manager\Views\Settings\User.cshtml"
     if (Model.Extensions.Count > 0) {
        
            
            #line default
            #line hidden
            
            #line 97 "..\..\Areas\Manager\Views\Settings\User.cshtml"
   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
            
            #line 97 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                          
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" class=\"grid_3\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 102 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                          Write(Piranha.Resources.Settings.ChangePassword);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 106 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Password, Piranha.Resources.Global.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 108 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.PasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 111 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.PasswordConfirm, Piranha.Resources.Global.Confirm));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 113 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.PasswordFor(m => m.PasswordConfirm));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                    ");

            
            #line 114 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.PasswordConfirm));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

            
            #line 120 "..\..\Areas\Manager\Views\Settings\User.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
